version: "3"

services:

  product-db:
    build:
      context: .
      dockerfile: products-db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: cloudcom2018
    expose:
      - "13306"
    ports:
      - "13306:3306"
    networks:
      cloudcomnet:
        ipv4_address: 172.18.0.23
        aliases:
          - db.products.cloudcom


  reviews-db:
    build:
      context: .
      dockerfile: reviews-db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: cloudcom2018
    expose:
      - "23306"
    ports:
      - "23306:3306"
    networks:
      cloudcomnet:
        ipv4_address: 172.18.0.13
        aliases:
          - db.reviews.cloudcom


  ratings-db:
    build:
      context: .
      dockerfile: ratings-db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: cloudcom2018
    expose:
      - "33306"
    ports:
      - "33306:3306"
    networks:
      cloudcomnet:
        ipv4_address: 172.18.0.3
        aliases:
          - db.ratings.cloudcom


  ratings:
    build:
      context: .
      dockerfile: ratings/Dockerfile
    restart: on-failure
    networks:
      cloudcomnet:
        ipv4_address: 172.18.0.4
        aliases:
          - app.ratings.cloudcom
    expose:
      - "18082"
    ports:
      - "18082:8082"
    depends_on:
      - ratings-db
      - reviews-db
      - product-db


  reviews:
    build:
      context: .
      dockerfile: reviews/Dockerfile
    restart: on-failure
    networks:
      cloudcomnet:
        ipv4_address: 172.18.0.14
        aliases:
          - app.reviews.cloudcom
    expose:
      - "28082"
    ports:
      - "28082:8081"
    depends_on:
      - reviews-db
      - ratings-db
      - product-db


  product:
    build:
      context: .
      dockerfile: product/Dockerfile
    restart: on-failure
    networks:
      cloudcomnet:
        ipv4_address: 172.18.0.24
        aliases:
        - app.product.cloudcom
    expose:
    - "38082"
    ports:
    - "38082:8080"
    depends_on:
    - reviews-db
    - ratings-db
    - product-db



networks:
  cloudcomnet:
   ipam:
     driver: default
     config:
       - subnet: 172.18.0.0/16



